apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  strategy:
    type: Recreate
  replicas: 6
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: configmap-volume
          mountPath: /usr/share/nginx/html

      volumes:
      - name: configmap-volume
        configMap:
          name: cm1
---
apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: default
  type: NodePort